The Map.forEach loop with 2 arguments (key and value) was crashing with NoClassDefFoundError exception on devices with older android OS version, as the method was not available in android at runtime. Replaced with Map.forEach with a single argument. (#213)
Co-authored-by: Tomek Jurkowski <tomasz@scandit.com>
(cherry picked from commit 0cc927a9d21408126ec2682e61e53249075ac0a3)